### ISSUE TITLE
Obstruction Line On Home  & Services Page

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#100]
**Describe the bug**
An obstruction line is found on both the Home Page and Services page that goes across the screen horizontally. 

**To Reproduce**
1. Go to 'Sign In' on www.inlightzambia.com
2. Navigate to 'Home Page & Services Page'
3. See error

**Expected behavior**
To see no line on either page.

**Screenshots**
![Home Page - Obstruction Line](https://github.com/tumavideo/yop/assets/145007727/1c4f4a77-30c4-4fa9-90f2-710cc19c0f37)
![Services Page - Obstruction Line](https://github.com/tumavideo/yop/assets/145007727/f32c40a8-3752-4642-9e1e-77d0256c6ef3)

**Desktop (please complete the following information):**
Chrome

**Smartphone (please complete the following information):**
N/A

**Additional context**
Obstruction only found on desktop when signed into ILZ.

**Comment by noelsich** [comment]
hey guys here it's the --tw-ring-offset-color  for the class "bg-white relative isolate" that's causing the problem

**Comment by tonydollarsign** [comment]
Fixed with #159
