### ISSUE TITLE
Warning For Repeated Email On Sign Up Page

### ISSUE THREAD

**Issue by noelsich** [tumavideo/yop#113]
**Describe the bug**
There is no warning for a repeated email on the inlight sign up page

**To Reproduce**
1. Go to 'inlight zambia sign up page'
2. fill in fields with an already used email (noelsich@gmal.com)
3. click on the sign up button 

**Expected behavior**
a notification stating 'email has already been used' before clicking sign up

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Microsoft edge]
 
**Additional context**
No link was sent to the email (noelsich@gmail.com) to  confirm the  sign up.

**Comment by Mwimwii** [comment]
Got it, we need to sit down on the ending screen. 
If a user uses an existing email, our system already sends them a magic link for login. 

But I also agree that we should through an error, for the user experience

**Comment by Mwimwii** [comment]
I think this issue can tie well with the other issue @Zikhalo posted  #79

**Comment by noelsich** [comment]
Yeah, that is a more permanent solution

**Comment by noelsich** [comment]
@Mwimwi did you close this one because of #79 was complete?
