### ISSUE TITLE
Deleting Uploaded Files

### ISSUE THREAD

**Issue by noelsich** [tumavideo/yop#119]
**Is your feature request related to a problem? Please describe.**
There's no option to delete an uploaded resume

**Describe the solution you'd like**
A cross at the beginning of the "uploaded resume" tab giving the option to delete an  uploaded resume 

**Describe alternatives you've considered**
a delete button next to the download button

**Comment by tonydollarsign** [comment]
As shown in #157 we overwrite the old one with a new one. Not even showing the last 3 to reduce confusion. We don't want users to delete their resumes but if they want they can delete their accounts.

**Comment by noelsich** [comment]
> As shown in #157 we overwrite the old one with a new one. Not even showing the last 3 to reduce confusion. We don't want users to delete their resumes but if they want they can delete their accounts.

Nice if you don't want to keep it delete your account ... Genius!!!!
