### ISSUE TITLE
Profile Page Access Issue

### ISSUE THREAD

**Issue by noelsich** [tumavideo/yop#120]
**Describe the bug**
A logged out user can access the inlight profile page by clicking a link and upload and see uploaded resumes

**To Reproduce**
1. Go to the 'inlight website and log out of inlight account'
2. Go to [link](https://www.inlightzambia.com/profile)
5. Scroll down to 'Uploaded resumes'
7. See resumes uploaded while users were offline

**Expected behavior**
This page should not be accessible while one is offline

**Screenshots**
![not logged in](https://github.com/tumavideo/yop/assets/123343039/72dd01ac-033f-4327-a2f8-e22f2dcdb7ba)

**Smartphone (please complete the following information):**
 - Device: [Tecno pop5]
 - OS: [Android 11]
 - Browser  [chrome, opera mini]

**Comment by Zikhalo** [comment]
Can we double check this one. I tried the steps and was directed to the sign in page

**Comment by tonydollarsign** [comment]
@noelsich see @Zikhalo 's comment

**Comment by Mwimwii** [comment]
This was fixed in #137
