### ISSUE TITLE
Clickable Opportunities Tab

### ISSUE THREAD

**Issue by noelsich** [tumavideo/yop#131]
**Is your feature request related to a problem? Please describe.**
People usually don't see the "see more" link on the opportunities posted on inlight, they attempt to click anywhere on the  tab

**Describe the solution you'd like**
A clickable opportunity tab 
![filter](https://github.com/tumavideo/yop/assets/123343039/788c5591-53c0-48c5-b62a-c4972593f633)

**Comment by tonydollarsign** [comment]
This was fixed [here](https://github.com/tumavideo/yop/commit/8ee73d84cc9aa336190b80a22cdd7a92657d26b9). Push to main, naughty @Mwimwii
