### ISSUE TITLE
Less Opportunities on Web Than on SANITY

### ISSUE THREAD

**Issue by noelsich** [tumavideo/yop#142]
Describe the bug
Less opportunities are appearing on the opportunities pages than the ones appearing on SANITY

To Reproduce

Go to the 'inlight App and sign in'
click the "opportunities" button
Click on 'Select Opportunity'
select any opportunity
Compare the number of opportunities on SANITY with the ones on the web version
See error
Expected behavior
The list of opportunities should keep scrolling until it states "No more opportunities to Explore"

O.S [Windows 11]
Browser [MicrosoftEdge]

**Comment by noelsich** [comment]
@tonydollarsign  The same issue on the 'skills' page was not addressed I assume its the same with funding.

**Comment by noelsich** [comment]
@Mwimwii @tonydollarsign @MichaelChuba @Zikhalo this is important... if someone could duplicate the work done with the jobs page.

**Comment by tonydollarsign** [comment]
Agreed with @Zikhalo this works as expected.
