### ISSUE TITLE
Step-by-Step Registration Process

### ISSUE THREAD

**Issue by Mwimwii** [tumavideo/yop#144]
Figma: [Link Here](https://www.figma.com/file/dZgVQeehKO206H2u4TXiyp/Multi-step-Form-Figma-Template-%7C-BRIX-Templates-(Community)?type=design&node-id=901%3A13905&mode=design&t=B0b7GAnUEPX6bq84-1)

**Is your feature request related to a problem? Please describe.**
Currently, our application's registration process lacks a step-by-step approach, which can be confusing for new users and may lead to incomplete registrations.

**Describe the solution you'd like**
I would like to propose the implementation of a step-by-step registration process using a form stepper method. This method would guide users through each registration step, ensuring that all required information is provided before proceeding to the next step.

**Describe alternatives you've considered**
An alternative approach could be to keep the current registration form layout, but this may not provide the same level of clarity and user guidance as a step-by-step process.

**Additional context**
Implementing a step-by-step registration process would improve the user experience for new users and increase the likelihood of successful registrations.

**Comment by Zikhalo** [comment]
"You're almost set to start exploring opportunities (and services)! We just need some information to proceed"
