### ISSUE TITLE
Resume Upload during Onboarding

### ISSUE THREAD

**Issue by Mwimwii** [tumavideo/yop#145]
Figma: [Link Here](https://www.figma.com/file/dZgVQeehKO206H2u4TXiyp/Multi-step-Form-Figma-Template-%7C-BRIX-Templates-(Community)?type=design&node-id=901%3A14054&mode=design&t=B0b7GAnUEPX6bq84-1)

**Is your feature request related to a problem? Please describe.**
Currently, our application does not allow users to upload their resumes during the onboarding process, which may result in a disjointed experience for users who need to provide this information.

**Describe the solution you'd like**
I would like to propose the addition of a resume upload feature as part of the user onboarding process. This would allow users to upload their resumes seamlessly during registration, ensuring that all required documents are submitted at the same time.

**Describe alternatives you've considered**
An alternative approach could be to ask users to upload their resumes after completing the registration process, but this may lead to delays in processing user applications.

**Additional context**
Including a resume upload feature during onboarding would streamline the user experience and make the application process more efficient for both users and administrators.

**Comment by Zikhalo** [comment]
"We'd like to seamlessly connect you with opportunities and in order to do so, we'll need your latest and greatest resume"/"We'd like to fine tune your resume and in order to do so, we'll need your latest and greatest resume"
