### ISSUE TITLE
Share Button

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#15]
**Is your feature request related to a problem? Please describe.**
Adding another user friendly feature that can be priced for sale.

**Describe the solution you'd like**
Introducing a “Share" button for users who are signed up to the platform (20/09/23).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anthonysikaneta** [comment]
@Zikhalo about the **Instagram Share Button** specifically:

Instagram doesn't provide a direct share button for websites like Facebook and Twitter. Instagram sharing is primarily done through the mobile app. However, you can encourage users to share content on Instagram by providing a caption and a "Follow on Instagram" link.
