### ISSUE TITLE
Social Login Not Using Referral Code

### ISSUE THREAD

**Issue by Mwimwii** [tumavideo/yop#153]
**Is your bug report related to a problem? Please describe.**
When users register or log in using the social login option, the referral code is not being applied or used in the registration process.

**Describe the issue**
Currently, when users register or log in using the social login option (e.g., Google Auth), the referral code is not being captured or utilized in the registration process. This means that users who sign up through social login are not associated with a referral code, which impacts our ability to track referrals and provide incentives for our promotion.

**Steps to reproduce the issue**

1.     Navigate to the registration page.
2.     Choose the social login option (e.g., Google Auth) to register.
3.     Complete the registration process.
4.     Verify that the referral code is not applied or displayed in the user profile or confirmation page.

**Expected behavior**
When users register or log in using the social login option, the system should capture and apply the referral code to the user's account. This ensures that all users, regardless of the registration method, are associated with a referral code for tracking and promotional purposes.

**Actual behavior**
Currently, the social login option does not capture or apply the referral code, resulting in users being registered without a referral code.

**Impact of the issue**
Users who sign up through social login are not associated with a referral code.
Inability to track referrals and incentivize user growth for users who sign up through social login.

**Additional context**
This issue impacts our ability to effectively track and promote our referral program, especially during our current promotion. It is crucial to ensure that all users, regardless of the registration method, are included in the referral program to maximize its effectiveness.

**Comment by tonydollarsign** [comment]
Fixed in #154
