### ISSUE TITLE
SupaBase

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#16]
**Is your feature request related to a problem? Please describe.**
Finding a designated home for the "User" tab on Sanity.

**Describe the solution you'd like**
Having the “User” section on Sanity fall on its own on SupaBase, a platform that will generate detailed reports and analytics (20/09/23).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anthonysikaneta** [comment]
This is done - currently part of sign up process.

TODO - create fix for ability to re-register with the same email, [issue](https://github.com/supabase/gotrue-js/issues/320) with the original platform (supabase).
