### ISSUE TITLE
Remove "Get Started" Banner At The Bottom Of The Home Page

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#162]
**Is your feature request related to a problem? Please describe.**
The "Get Started" banner advertises the option to showcase opportunities which isn't in place at the moment.

**Describe the solution you'd like**
Remove the bottom banner seeing as nothing is currently being showcased by organizations.

**Describe alternatives you've considered**
Changing the wording to, "Discover a variety of opportunities from jobs, skills and funding avenues. It's all just one click away!"

**Additional context**
![Screenshot 2024-01-15 080316](https://github.com/tumavideo/yop/assets/145007727/871a797a-56fb-4584-b9f6-b603826e5176)

**Comment by tonydollarsign** [comment]
@Zikhalo which do you prefer, removing it or changing the wording?

**Comment by Zikhalo** [comment]
Change
