### ISSUE TITLE
Add Mobile App Banner

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#163]
**Is your feature request related to a problem? Please describe.**
There is nowhere on the website highlighting the mobile app.

**Describe the solution you'd like**
Replacing the NAPSA banner with a Mobile App banner as shared in slack, and another banner falling on the left side of the Profile page

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot 2024-01-16 064302](https://github.com/tumavideo/yop/assets/145007727/2e8acf20-7850-46fe-8043-65780f1bdc8a)

![Screenshot 2024-01-16 072545](https://github.com/tumavideo/yop/assets/145007727/073f7b02-e668-40bb-93c3-ac3068238270)

**Comment by tonydollarsign** [comment]
@Zikhalo this doesn't require development. You can go into console and edit the NAPSA banner and see how it looks.

<img width="687" alt="Screenshot 2024-01-17 at 06 58 05" src="https://github.com/tumavideo/yop/assets/89261448/a8560fb8-d54d-47be-9e1d-8970c013c75d">

Of course the mobile app isn't a goverment program but maybe we should change the name to "Ads".

**Comment by Zikhalo** [comment]
Change to "Ads"

**Comment by noelsich** [comment]
This one was done on cosole
