### ISSUE TITLE
upload Symbol

### ISSUE THREAD

**Issue by noelsich** [tumavideo/yop#177]
**Describe the bug**
When using the drop to upload feature the upload symbol appears cut

**To Reproduce**
1. Go to the Inlight Zambia website
2. Navigate to the profile page 
3. Attempt to upload resume using the drop to upload feature

**Expected behavior**
The symbol should take the full box as a drop is being initiated

**Screenshots**
![upload symbol](https://github.com/tumavideo/yop/assets/123343039/58eea2dd-8634-4eb8-bb50-d53fe738301d)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [Microsoft edge]

**Comment by tonydollarsign** [comment]
Tested on version 122.0.2365.92 of MS Edge
