### ISSUE TITLE
Console to Sanity

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#18]
**Is your feature request related to a problem? Please describe.**
Deviate from using the console.

**Describe the solution you'd like**
Having the government programs and testimonies from the console run through Sanity (20/09/23).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anthonysikaneta** [comment]
@MichaelChuba the best place to start with this is the example found on [this](https://www.sanity.io/docs/js-client) page. Once the sanity client is installed, you will only need your project id: d9p0l1rj and SANITY_SECRET_TOKEN // Only if you want to update content with the client. Let me know if there is anything unclear or that you need help with.

**Comment by MichaelChuba** [comment]
Okay noted. Send me the sanity token. The one you sent has expired.
