### ISSUE TITLE
Sign Up Page

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#55]
**Is your feature request related to a problem? Please describe.**
1. Forgot password shows on the sign up page. What password is forgotten when you haven't signed up?
2. Remember me shows on the sign up page. What is being remembered when you haven't signed up?
3. Once signed in, the sign in prompt still shows.

**Describe the solution you'd like**
1. Forgot password shouldn't show on the sign up page. 
2. Remember me shouldn't show on the sign up page.
3. Once signed in, the profile icon should show instead of the prompt to sign in.

**Describe alternatives you've considered**
N/A

**Additional context**

![WhatsApp Image 2023-10-31 at 09 12 39_6a27c960](https://github.com/tumavideo/yop/assets/145007727/239bfbc0-0e08-4da7-b2b5-dd8c05bcf901)

**Comment by MichaelChuba** [comment]
That task falls under Tony's responsibility, as he is the one who implemented the signup and forgot features.
