### ISSUE TITLE
Adding Skills and Industries to Profile 

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#57]
**Is your feature request related to a problem? Please describe.**
No way of gathering information to see what skills and industries users are into.

**Describe alternatives you've considered**
Have optional fields to fill out on the "Your Profile" page below "Phone". Which skill(s) are you interested in?... What industry are you interested in?... How did you find out about us?

**Additional context**
N/A

![WhatsApp Image 2023-10-31 at 10 09 32_d8744533](https://github.com/tumavideo/yop/assets/145007727/ccf0946e-3363-4cc3-a2d1-88bce934a375)

**Comment by MichaelChuba** [comment]
That task falls under Tony's responsibility, as he is the one who implemented the Profile.

**Comment by Mwimwii** [comment]
Can a new issue be made for this? Its very hard to track the associated pr's if they share an issue @Zikhalo 
 
>2. Have optional fields to fill out on the "Your Profile" page below "Phone". Which skill(s) are you interested in?... What industry are you interested in?... How did you find out about us?

**Comment by anthonysikaneta** [comment]
@Mwimwii @Zikhalo I've made the necessary changes
