### ISSUE TITLE
Profile Page (Mobile Browser)

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#58]
**Is your feature request related to a problem? Please describe.**
Profile page isn't easily accessible unless you know how to manually input the web address.

**Describe the solution you'd like**
Have a spot for "Your Profile". Suggestion is for it to fall below "Sign Out"

**Describe alternatives you've considered**
N/A

**Additional context**
![image](https://github.com/tumavideo/yop/assets/145007727/c34cb487-2901-4e43-a8d6-ae80d76f0733)

**Comment by MichaelChuba** [comment]
That task falls under Tony's responsibility, as he is the one who implemented the Profile.
