### ISSUE TITLE
Contact Info

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#61]
**Is your feature request related to a problem? Please describe.**
Under "Contact Info", the contact info either falls beside or below Email, Cell, Work on both mobile and desktop.

**Describe the solution you'd like**
Under "Contact Info", the contact info should fall below Email, Cell, Work on both mobile and desktop.

**Describe alternatives you've considered**
N/A

**Additional context**
![WhatsApp Image 2023-11-01 at 04 24 57_53dc8e5f](https://github.com/tumavideo/yop/assets/145007727/b3fb0958-64ac-4b84-b20e-bf86e7fef76c)

**Comment by anthonysikaneta** [comment]
Won't fix
