### ISSUE TITLE
Change CTA Text

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#64]
**Is your feature request related to a problem? Please describe.**
1. Before signing in, the nomenclature, "Ready to explore community services? Start your free trial today.", shown on the Services page needs to be revised. 

**Describe the solution you'd like**
1. The nomenclature should say...
"Ready to explore community services? Get started today."
Sign up (button) followed by "Learn more"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anthonysikaneta** [comment]
Removed ZamPortal button stuff from ticket
