### ISSUE TITLE
Small Logo Size (Desktop)

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#65]
**Is your feature request related to a problem? Please describe.**
The logo size on the top left on desktop view is quite small in comparison to the logo that shows on the About page. 
*Note: the sizing of the logo on mobile view aligns with with the logo on the About page. 

**Describe the solution you'd like**
Increase the sizing of the logo on desktop view to replicate the one found on the About page

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anthonysikaneta** [comment]
@Zikhalo please attach screenshots

**Comment by Zikhalo** [comment]
![Screenshot 2023-11-01 105203](https://github.com/tumavideo/yop/assets/145007727/e4048df6-6d0f-44de-9858-859415aa9660)
![WhatsApp Image 2023-11-01 at 10 49 21_1ae7629f](https://github.com/tumavideo/yop/assets/145007727/f1e62c14-d354-4c72-8df1-b85bb7c785c0)

**Comment by anthonysikaneta** [comment]
I won't fix it, over to @MichaelChuba if you really want to.
