### ISSUE TITLE
Small Leaderboard (728 x 90px) on Community Page

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#66]
**Is your feature request related to a problem? Please describe.**
Leaderboard (728 x 90px) is smaller on the Community page than the rest of the pages (Opportunities and Services).

**Describe the solution you'd like**
To have the Leaderboard (728 x 90px) align with the rest of the ads on the other pages.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anthonysikaneta** [comment]
@Zikhalo screenshot please

**Comment by Zikhalo** [comment]
![Screenshot 2023-11-01 112715](https://github.com/tumavideo/yop/assets/145007727/55992932-a5a5-4c70-8950-7b1b9e8ff874)
![Screenshot 2023-11-01 112727](https://github.com/tumavideo/yop/assets/145007727/aee14d1d-04d5-463e-9bb2-8acc43f25223)
![Screenshot 2023-11-01 112744](https://github.com/tumavideo/yop/assets/145007727/aeef05f2-7476-4697-9d48-5190914cefb7)

**Comment by Zikhalo** [comment]
I would suggest this quick fix to @MichaelChuba who has the least amount of tickets...

**Comment by Zikhalo** [comment]
@Mwimwii seeing as there no longer a leaderboard ad, this ticket can be closed

**Comment by Zikhalo** [comment]
Seeing as there no longer a leaderboard ad, this ticket can be closed
