### ISSUE TITLE
Call to Action (Community Page) - Get Notified

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#69]
**Is your feature request related to a problem? Please describe.**
The call to action, "Get notified when new content is added", at the bottom of the page can be revised...

**Describe the solution you'd like**
"Get Notified"
"Follow and get the up to date new content"
"Follow WhatsApp Channel" (button)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by anthonysikaneta** [comment]
"Follow and get the up to date new content"

Remove "the" definitely
Also it is "up-to-date"

but do we want "up-to-date" and "new"?
