### ISSUE TITLE
One Button Sign In Google

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#79]
**Is your feature request related to a problem? Please describe.**
There seems to be a disconnect with users fully signing (Sign Up + completing Profile)  up on the platform for various reasons...

**Describe the solution you'd like**
To make for a smoother sign up process, have users be able to sign in with their Google account. The same details from the Google account could then be used to fill out the fields found on the "Profile" page (First name, Last name, Email address, Phone)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by tonydollarsign** [comment]
Fixed in [!138](https://github.com/tumavideo/yop/pull/138)
