### ISSUE TITLE
ZamPortal Services Video

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#9]
**Is your feature request related to a problem? Please describe.**
The instructional video for ZamPortal Services needs revamping.

**Describe the solution you'd like**
Creating a new instructional video for ZamPortal Services with stronger visuals and different background music (03/10/23). 

**Describe alternatives you've considered**
N/A

**Additional context**
Current instructional video - https://yop-nsti-git-tailwind-refactor-zyop.vercel.app/govt/64cd10aa1d8c0f081aa5e8b8

**Comment by MichaelChuba** [comment]
This has been fixed. This ticket is closed now.
