### ISSUE TITLE
Signing Out From Profile Page Stays On Profile Page

### ISSUE THREAD

**Issue by Zikhalo** [tumavideo/yop#97]
**Is your feature request related to a problem? Please describe.**
When signing out from the profile page, it should bring you to the sign in page. Instead you remain on the profile page.

**Describe the solution you'd like**
Signing out from profile page should direct you to either the home page or to the sign in page.

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot 2023-11-16 052700](https://github.com/tumavideo/yop/assets/145007727/4bbf7bb7-f6f3-4072-8584-9497fa9692ae)

**Comment by Zikhalo** [comment]
*Note: This also applies on the mobile side @MichaelChuba. Would an additional ticket be needed for this?

**Comment by Zikhalo** [comment]
Can we double check this one. I tried the steps and was directed to the sign in page

**Comment by tonydollarsign** [comment]
@noelsich see @Zikhalo 's comment

**Comment by Mwimwii** [comment]
Fixed in #137 last week
